import type { Metadata } from "next";
import { Albert_Sans, Spectral } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/navbar";
import { cn } from "@/lib/utils";

const spectral = Spectral({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  style: ["normal", "italic"],
  variable: "--font-heading",
});

const albertSans = Albert_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full antialiased font-sans",
        albertSans.variable,
        spectral.variable,
      )}
    >
      <body className={cn("min-h-full flex flex-col", albertSans.className)}>
        <Navbar />
        <div className="flex-1">{children}</div>
      </body>
    </html>
  );
}
